//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Settings struct {
	RepositoryOwner string `sql:"primary_key"`
	RepositoryName  string `sql:"primary_key"`
}
